import Head from "next/head";
import { Heading, Text, Center, Link } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center h={"full"} as={"main"} textAlign={"center"}>
        <div>
          <Heading size={"lg"} mb={2}>
            The Eisenhower Template
          </Heading>
          <Text mb={3}>
            A Typescript + Next.js template with nice defaults and no nonsense.
          </Text>
          <Text>
            <i>
              Created by{" "}
              <Link href={"https://github.com/wyatt"}>Wyatt Sell</Link>
            </i>
          </Text>
        </div>
      </Center>
    </>
  );
}
